version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - go-api
  go-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"